### ISSUE TITLE
请问直接访问8080端口就行吗

### ISSUE THREAD

**Issue by ghost** [Yuxiao97/SpringBootFileUploadWithProgress#1]

**Comment by ghost** [comment]
> _没有提供说明。_
知道啦，访问uploadPage
thanks

**Comment by ghost** [comment]
请问上传文件是传到哪里了呢

**Comment by yuxiao97** [comment]
> 请问上传文件是传到哪里了呢

new File("d:/"+file.getOriginalFilename())；
由于演示用，所以硬编码在程序中了。

**Comment by yuxiao97** [comment]
是的 默认是8080端口 可直接访问
